# Generated by Django 5.0.6 on 2024-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("TELLER", "Teller")],
                        default="CUSTOMER",
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("mobile_number", models.CharField(blank=True, max_length=15)),
                ("pin", models.CharField(blank=True, max_length=6)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[("INDIA", "India"), ("UK", "United Kingdom")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_customer", models.BooleanField(default=False)),
                ("is_teller", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.useraccount",),
        ),
        migrations.CreateModel(
            name="Teller",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.useraccount",),
        ),
    ]
