# Generated by Django 5.0.6 on 2024-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraccount_groups_useraccount_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
