# Generated by Django 5.0.6 on 2024-05-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralLedgerAccount",
            fields=[
                (
                    "account_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("account_name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
