# Generated by Django 5.0.6 on 2024-05-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "state_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("state_name", models.CharField(max_length=50)),
                (
                    "country_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "city_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("city_name", models.CharField(max_length=100)),
                (
                    "country_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.country",
                    ),
                ),
                (
                    "state_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.state",
                    ),
                ),
            ],
        ),
    ]
