# Generated by Django 5.0.6 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_alter_city_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "type_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=50)),
                ("type_description", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
