# Generated by Django 5.0.6 on 2024-05-25 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0003_accounttype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccounts",
            fields=[
                ("sid", models.AutoField(primary_key=True, serialize=False)),
                ("acc_number", models.CharField(blank=True, max_length=15)),
                (
                    "bal_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("currency", models.CharField(default="INR", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DORMANT", "Dormant"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "acc_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.accounttype",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
