# Generated by Django 5.0.6 on 2024-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccounts",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DORMANT", "Dormant"),
                    ("CLOSED", "Closed"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
