# Generated by Django 5.0.6 on 2024-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0002_alter_bankaccounts_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccounts",
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
            },
        ),
        migrations.AlterField(
            model_name="bankaccounts",
            name="status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Inactive"),
                    ("ACTIVE", "Active"),
                    ("DORMANT", "Dormant"),
                    ("CLOSED", "Closed"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
